Cache non-configurable node set congestion costs
verilog-to-routing/vtr-verilog-to-routing pull request #1615
Opened 2020-12-17 00:22 UTC by HackerFoo

#### Description
VPR spends a lot of time adding costs in `get_rr_cong_cost()` when used with SymbiFlow architectures, which is called many billions of times. This PR adds a cache for those costs, and invalidates entries when they should be updated.

#### Related Issue

#### Motivation and Context
This is to improve VPR's performance.

#### How Has This Been Tested?
Performance measurements are still in progress.

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2020-12-17 00:24 UTC, HackerFoo commented
@litghost This approach should preserve the same VPR's previous behavior. I'm collecting data to see if it is faster.

2020-12-17 22:02 UTC, HackerFoo commented
I've updated the algorithm based on discussion today.

2020-12-17 22:05 UTC, litghost commented
> I've updated the algorithm based on discussion today.

How does the performance look?  Hopefully the various tests go green.

2020-12-17 22:14 UTC, litghost commented
Looks like the strong tests are failing?  

Example:
```
Error: Executable vpr failed
	full command:  /usr/bin/env time -v /tmpfs/src/github/vtr-verilog-to-routing/vpr/vpr k4_N8_topology-0.85sL2-0.15gL4-on-cb-off-sb_22nm_22nm_nonLR.xml const_false --circuit_file const_false.pre-vpr.blif --gen_post_synthesis_netlist on --sweep_dangling_primary_ios off --sweep_constant_primary_outputs off --min_route_chan_width_hint 2
	returncode  :  139
	log file    :  /tmpfs/src/github/vtr-verilog-to-routing/vtr_flow/tasks/regression_tests/vtr_reg_strong/strong_post_routing_sync/run001/k4_N8_topology-0.85sL2-0.15gL4-on-cb-off-sb_22nm_22nm_nonLR.xml/const_false.blif/common/vpr.out
failed: Executable vpr failed (took 0.15 seconds)
```

2020-12-17 22:31 UTC, HackerFoo commented
Segfault in get_rr_cong_cost(). I forgot to change the size of `rr_non_config_node_cong_base_costs`. One per node, not one per set.

2020-12-18 00:50 UTC, HackerFoo commented
It doesn't seem to converge. I have more work to do.

2020-12-18 00:54 UTC, HackerFoo commented
I suspect that non-configurable nodes are now being over-adjusted, because multiple paths in the same routing tree could pass through the same set, but I'm not sure if this is possible.

2021-01-05 18:20 UTC, litghost requested changes
CI failure?
```
[Fail]
buffered_flyover_wires.xml/raygentop.v/common vpr_status Task value 'exited with return code 134' does not match golden 'success'
```

2021-01-05 22:28 UTC, HackerFoo commented
I have marked this WIP because I don't think the simple fix here worked for https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1619, so I'll have to try something more sophisticated.

2021-06-23 16:18 UTC, closed without merging