place: fix case in which PR region does not have constraints
verilog-to-routing/vtr-verilog-to-routing pull request #1713
Opened 2021-04-23 12:20 UTC by acomodi

Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

#### Description

The new partition region code might not take into account that partition regions are not being set and constraints are not initialized. This PR is an attempt at fixing this.

#### Related Issue

https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1711

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2021-04-23 12:54 UTC, acomodi commented
cc @sfkhalid @vaughnbetz

2021-04-23 16:39 UTC, sfkhalid commented
@acomodi During clustering each new cluster block is assigned an empty PartitionRegion to start with, which can then be either populated with constraint regions or not populated with constraint regions. I think this check is a good one to have, but I am not sure if it is the cause of the issue

2021-04-23 17:09 UTC, acomodi commented
@sfkhalid Ok, I'd need to investigate a bit more and find the source of the issue. The question I am trying to answer is also why this behaviour was not caught previously by CI, so either some change not related to the Partition Regions might have indirectly caused the root issue that leads to this failure.

One thing I wanted to test was whether this was a fix in the right direction, but kokoro did not start for some reason

2021-04-23 17:28 UTC, vaughnbetz requested changes
I don't think we want the new code. cluster_constraints is stored as a vector indexed by cluster block number.  So this change makes the code longer and I think takes us from an O(1) lookup to an O(n) search.

2021-04-23 17:39 UTC, vaughnbetz commented
I looked into the .keys() implementation. The code change would definitely take us from O(1) to O(N) in code that can be performance critical.  We should not make this change.

2021-04-26 06:20 UTC, acomodi commented
@vaughnbetz Sure, I will change the fix. As it turns out, there is some other kind of problem preventing the Nightly build to complete successfully.

2021-05-26 21:47 UTC, vaughnbetz commented
@acomodi, @sfkhalid  : I think this fix is no longer needed, as Sarah now has put back code to ensure the original function (which checked if you had a partition region on a block) works in all cases / flows. @sfkhalid : can you confirm that the code is now safe (will return false) for blocks with no partition region?  If so, we can close this PR and not put back the code (which looks slow).

2021-05-26 22:03 UTC, sfkhalid commented
> @acomodi, @sfkhalid : I think this fix is no longer needed, as Sarah now has put back code to ensure the original function (which checked if you had a partition region on a block) works in all cases / flows. @sfkhalid : can you confirm that the code is now safe (will return false) for blocks with no partition region? If so, we can close this PR and not put back the code (which looks slow).

Yes, this fix is no longer needed. The function returns false for blocks with an empty partition region. This will work in any flow because there is a routine now that assigns each cluster a partition region (empty or otherwise if it has constraints) in the case where the pack stage is loaded rather than performed.

2021-05-26 22:05 UTC, vaughnbetz commented
Closing this PR as unneeded.

2021-05-26 22:05 UTC, closed without merging