Moving the rrgraph_read/ rrgraph_write to libs/rrgraph
verilog-to-routing/vtr-verilog-to-routing pull request #2000
Opened 2022-03-16 14:42 UTC by Raza-jafari-RS

#### In this PR the  rrgraph_read/ rrgraph_write are moved to libs/rrgraph
Previously the  rrgraph_read/ rrgraph_write were present in the vpr/src/route which is now moved to  libs/rrgraph/src/base 

#### Related Issue

#### Motivation and Context
As devised by the mentor

#### How Has This Been Tested?

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2022-03-18 11:14 UTC, tangxifan requested changes
I checked the code changes. I believe that you should move all the relevant data structures required by the rr_graph_reader/writer to the ``librrgraph``.
The standard way is that 
- you go through the header files included by the rr_graph_writer.cpp and rr_graph_reader.cpp. 
- Find out what data structure it requires.
- For each data structure, create a separated header file and move it to ``librrgraph``.

If you feel confused, we can get on a call.

2022-03-18 11:14 UTC, tangxifan commented on libs/librrgraph/CMakeLists.txt
> +target_include_directories(librrgraph PUBLIC  ${PROJECT_SOURCE_DIR}/../EXTERNAL/ )
Please avoid to create a loop between VPR and this library. This library should not have any dependency on VPR. It should be self-contained.

In order to do this, you need to move all the related header and source files to the ``librrgraph``

Therefore, I think this line should not be modified.

2022-03-18 11:14 UTC, tangxifan commented on vpr/CMakeLists.txt
> +target_include_directories(libvpr PUBLIC  ${PROJECT_SOURCE_DIR}/../libs/librrgraph/src/base/ )
No need to modify this line. You just need to ensure that ``librrgraph`` is in the list of linked library.

2022-06-01 23:59 UTC, vaughnbetz commented
Waiting on a response to @tangxifan before reading this in detail ...

2022-06-02 02:07 UTC, tangxifan commented
> Waiting on a response to @tangxifan before reading this in detail ...

Hi @vaughnbetz Sorry for a delay in this PR. 
Actually, @Raza-jafari-RS is now assigned to another technical task related to VTR (developing EDIF/Verilog parser due to a higher priority). 
I have an intern who will join in 3 weeks and take over this work.
If you see an emergency, I can talk to @Raza-jafari-RS and see how to catch your deadline.

2022-06-04 18:15 UTC, vaughnbetz commented
That's fine. Thanks @tangxifan

2022-07-06 19:26 UTC, tangxifan commented
@vaughnbetz It is my pleasure to introduce @oscarcheng105 who is a summer intern at Rapidsilicon.
During his intern, he will contribute to VTR on the following aspects:

- Finish this PR
- Build unit tests for librrgraph and establish QoR tracking
- Benchmarking the efficiency of RRGraph data structure by comparing to the implementation in [rr_graph_obj.h](https://github.com/lnis-uofu/OpenFPGA/blob/master/vpr/src/device/rr_graph_obj.h)

@vaughnbetz 
If you are o.k. with the plan, would you mind to give him contributor access to the project? Thank you in advance.

2022-07-06 20:41 UTC, vaughnbetz commented
Welcome to vtr @oscarcheng105 !  I've added you to the committers list.

2022-07-21 19:14 UTC, tangxifan commented
Close this PR as #2101 is addressing this issue.

2022-07-21 19:14 UTC, closed without merging