Add Document on QoR Gathering for CI Tests
verilog-to-routing/vtr-verilog-to-routing pull request #2030
Opened 2022-05-10 18:02 UTC by amin1377

* Guidance on gathering QoR results for CI tests is added to the documentation
* Guidance on how to re-run CI tests is added to the documentation

@vaughnbetz

2022-05-12 15:12 UTC, vaughnbetz requested changes

2022-05-12 15:12 UTC, vaughnbetz commented on README.developers.md
> +Assume that we want to get the QoR results for "vtr_reg_nightly_test3". In artifact, there is a file named
artifact --> the artifact

2022-05-12 15:12 UTC, vaughnbetz commented on README.developers.md
> +In the case that you want to re-run the CI tests, go to the "Action" tab and find your workflow under Test Workflow.
This should probably be a separate topic/tab.  Should say CI tests sometimes fail for transient infrastructure issues, such as a server that provides some packages being temporarily unavailable. If this happens, you can re-run the CI tests by ....

2022-05-12 15:12 UTC, vaughnbetz commented on README.developers.md
> +### Example: CI Tests QoR Measurement
Make sure where we say how to get QoR that there is a link to this topic.  E.g.:

To generate QoR results on a suite of circuits you can either run a regression test locally (described below) or download a QoR artficact from the CI system (add link).

2022-05-12 15:12 UTC, vaughnbetz commented on README.developers.md
> +### Example: CI Tests QoR Measurement
Can mention that using the same machine (both CI or both not CI) is important for CPU comparisons.

2022-05-15 21:37 UTC, amin1377 commented
@vaughnbetz: I have made the changes suggested and deleted the documents related to Kokoro.

2022-06-01 23:18 UTC, vaughnbetz reviewed
Generally looks good; see the requested comment/change.

2022-06-01 23:18 UTC, vaughnbetz commented on README.developers.md
> +containing in this test suit(vtr_reg_nightly_test3.) For instance, results related to *vtr_reg_qor* are located in
containing -> contained
What is "each run" (e.g. run001)?  Do most tests just have one run, and a few have multiple runs (multiple compile tests that are being run against each other)?  If most tests just have run001 it's good to say that.

2022-06-01 23:41 UTC, merged