Issue #2078
verilog-to-routing/vtr-verilog-to-routing pull request #2092
Opened 2022-07-12 22:01 UTC by amin1377

This PR is created to address the [issue #2078](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2078)
@vaughnbetz

2022-07-16 15:01 UTC, vaughnbetz requested changes
Looks good; needs a make format and I suggest a couple of commenting updates.

2022-07-16 15:01 UTC, vaughnbetz commented on vpr/src/route/route_tree_timing.cpp
>      /* Adds rt_node to the proper free list.          */
Can put that as a function level comment (before function).

2022-07-16 15:01 UTC, vaughnbetz commented on vpr/src/route/route_tree_timing.cpp
>      /* Puts the rt_nodes and edges in the tree rooted at rt_node back on the
I'd move this comment to before the function declaration (our more common style now).

2022-07-17 21:24 UTC, amin1377 commented
> Looks good; needs a make format and I suggest a couple of commenting updates.

Done

2022-07-20 01:28 UTC, vaughnbetz commented
Still has a format failure -- I don't think you ran make format and commited and pushed?
Also has a read the docs failure, but no documentation was changed.  Infrastructure issue that hopefully goes away if you re-run?  If that one persists please file an issue on it.

2022-07-20 01:48 UTC, amin1377 commented
> Still has a format failure -- I don't think you ran make format and commited and pushed? Also has a read the docs failure, but no documentation was changed. Infrastructure issue that hopefully goes away if you re-run? If that one persists please file an issue on it.

Whoops...sorry. I didn't realize that I haven't run the make format. I ran it, and pushed the changes. Should the CI tests fail, I'll file an issue.

2022-07-21 17:05 UTC, vaughnbetz commented
Some infrastructure issues (one cmake, one read the docs).  Can you rerun to see if transient (hopefully the cmake one is at least) and file issues on anything that isn't transient?

2022-07-27 18:44 UTC, vaughnbetz commented
Only read the docs failures, which are fixed elsewhere (infrastructure).

2022-07-27 18:45 UTC, merged