packing refactor to use more STL containers
verilog-to-routing/vtr-verilog-to-routing pull request #2207
Opened 2022-11-17 20:42 UTC by MohamedElgammal

#### Description

In this PR, I have done some refactoring on the packing code to use more STL containers instead of hand-crafted linked lists. Besides that, I am adding more functions wrappers to t_cluster_placement_stats to prevent direct access to the data members. 

I am also adding a new context to support packing multithreading and some updates to the re-clustering API to support the packing iterative improvement project.

2022-11-21 15:21 UTC, MohamedElgammal commented on vpr/src/base/vpr_types.h
> +    ///<[0..num_pb_types-1] ptrs to linked list of valid primitives, for convenience, each linked list head is empty
update comment

2022-11-21 16:01 UTC, MohamedElgammal commented on vpr/src/base/vpr_types.h
> +    void move_primitive_to_inflight(int pb_type_index, std::unordered_multimap<int, t_cluster_placement_primitive*>::iterator& it);
why you increment the iterator

2022-11-21 17:33 UTC, vaughnbetz commented
Should add a QoR comparison (VTR, Titan anyway) so we know there are no surprises.

2022-11-21 18:32 UTC, vaughnbetz requested changes

2022-11-21 18:32 UTC, vaughnbetz commented on vpr/src/pack/cluster_placement.cpp
> +        if (!cluster_placement_stats->valid_primitives[i].empty() && primitive_type_feasible(molecule->atom_block_ids[molecule->root], cluster_placement_stats->valid_primitives[i].begin()->second->pb
Maybe a temporary variable for the long chain?

2022-11-21 18:32 UTC, vaughnbetz commented on vpr/src/pack/re_cluster_util.cpp
> +t_lb_router_data* lb_load_router_data(std::vector<t_lb_type_rr_node>* lb_type_rr_graphs, const ClusterBlockId& clb_index, const std::unordered_set<AtomBlockId>* clb_atoms) {
Update (or add) comment in header file about what clb_atoms being NULL means.

2022-11-23 19:55 UTC, MohamedElgammal commented on vpr/src/base/vpr_types.cpp
> +            == valid_primitives[i].begin()->second->pb_graph_node->pb_type) {
I have double-checked and found that t_pb_type doesn't have an index member. Hence, on the current data structure we should be checking that the type is the same. In future refactoring, a unique index can be added to each primitive pb_type (unique over its cluster block type) and this index can be used directly here.

2022-11-28 16:24 UTC, mithro commented
@hzeller - If you get a moment, as a C++ expert can you give this pull request a once over?

2022-11-28 18:03 UTC, vaughnbetz commented
Mohamed, can you run another seed on the vtr benchmarks to confirm the pack time ratios make sense -- the place times were highly variable so there may be some machine load effects going on.

2022-11-28 20:12 UTC, MohamedElgammal commented
@vaughnbetz I have added the run for another seed on a new sheet at the same spreadsheet. It shows that the pack time and place time are both almost equal to that of the master branch before the refactor. To mitigate the machine load effect in this run, I have run the master and the current branch simultaneously.

2022-11-28 20:17 UTC, vaughnbetz commented
Looks good, thanks.

2022-12-16 15:39 UTC, vaughnbetz commented
A couple of tests didn't run (vtr_reg_nightly3) and there's one yosys + partial mapping QoR change (looks benign). Updating to see if they go away, but this looks safe to merge.

2022-12-30 04:07 UTC, merged