[WIP] 3d Grid
verilog-to-routing/vtr-verilog-to-routing pull request #2246
Opened 2023-02-21 23:34 UTC by amin1377

In this PR we have changed DeviceGrid data structure to support multi-die FPGA architecture

2023-02-23 12:10 UTC, amin1377 commented
@vaughnbetz: This PR is ready for review

2023-02-26 22:58 UTC, amin1377 commented
@vaughnbetz: [Here](https://utoronto-my.sharepoint.com/:x:/g/personal/amin_mohaghegh_mail_utoronto_ca/EWqukqzqVZxFulMXoDH_dwYBphA2PsZkqLjZ1CppVqD1BA?e=vYSdxO) is the QoR results for VTR and Titan benchmark.

2023-03-02 23:06 UTC, saaramahmoudi reviewed
Just a quick reminder that we need to add documentation for device grid.

2023-03-09 16:39 UTC, vaughnbetz commented
VTR suite placement is 1.9% slower, Titan is 6.5% slower.  That is significant.  
- Check if the results are consistent across circuits, and/or run another seed.  Is this increase real?  It probably is, since you tell me you ran on the Savi machines in a consistent way (5 threads on master, let it finish, then 5 threads on new code.
- Can we get this back?  Worth profiling etc.  We'd rather not slow down by 6% if at all possible.

2023-03-09 16:43 UTC, vaughnbetz requested changes
Just started a review to give you a flavour of what I'm looking for.

2023-03-09 16:43 UTC, vaughnbetz commented on libs/libarchfpga/src/device_grid.cpp
What is this for?  Need a comment on purpose and use.

2023-03-09 16:43 UTC, vaughnbetz commented on libs/libarchfpga/src/device_grid.cpp
But these comments should go in the header file.

2023-03-16 12:26 UTC, amin1377 commented
> 

I ran the master branch and grid_3d for the titan benchmark again. I guess the last time I wasn't using the same number of threads, and the master branch was not the most recent one. Now the run-time of the two branches is almost similar.

2023-03-16 19:56 UTC, amin1377 commented
> Thanks, the new data looks good. I'll go through the code tonight or when we meet tomorrow and hopefully we can land this soon!

I have added comments to device_grid.h and device_grid.cpp, which are the two files where I made actual changes. The other files were modified because they previously accessed the t_grid_tile data structure directly. With the changes I made, other functions can now access this data structure only through the helper functions in DeviceGrid.

2023-03-24 21:00 UTC, tangxifan reviewed
Most of the code changes look good to me. Just need some clarification.

2023-03-28 12:40 UTC, amin1377 commented on libs/libarchfpga/src/device_grid.h
> +    std::vector<vtr::Matrix<t_grid_tile>> grid_;
The constructor of DeviceGrid would also accept a vector of 2d Matrix. VPR make the grid in "SetupGrid.cpp:build_device_grid." This function is also changes to pass a vector of grid to the DeviceGrid constructor.

2023-03-28 12:43 UTC, amin1377 commented on libs/libarchfpga/src/device_grid.h
> +    inline int get_num_layers() const {
Agreed! I removed num_layers_.

2023-04-07 20:23 UTC, amin1377 commented
Close this PR since it is merged in modeling_multi_die_stack.

2023-04-07 20:23 UTC, closed without merging