Migrate to Ubuntu 22.04 LTS
verilog-to-routing/vtr-verilog-to-routing pull request #2258
Opened 2023-03-20 06:36 UTC by Tulong4Dev

Migrate to Ubuntu 22.04 LTS

#### Description

- Provide dependency requirements for VTR to be developed and run on Ubuntu 22.04 LTS.

#### Related Issue

- Issue: https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2257

#### Motivation and Context

- The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 4/1/23

#### How Has This Been Tested?

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Infra update

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2023-03-22 02:29 UTC, tangxifan commented on .github/workflows/build_dependency_ubuntu-22.04.sh
> +# The package list is designed for Ubuntu 20.04 LTS
As discussed, I believe the script should be merged to the [install_dependencies.sh](https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/7a440a99b2efa59a9832540920156ca792093bab/.github/workflows/test.yml#L121)

Also the dependencies in https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/7a440a99b2efa59a9832540920156ca792093bab/.github/scripts/hostsetup.sh#L23-L72

should be updated as well.

2023-03-22 02:29 UTC, tangxifan commented on .github/workflows/test.yml
> +    container: ubuntu:jammy
All the other ``runs-on: ubuntu-18.04`` should be updated as well.

2023-03-22 17:45 UTC, tangxifan commented on .github/scripts/hostsetup.sh
> +    cmake \
Try to remove cmake from the list here. As cmake is installed later.

2023-03-22 17:54 UTC, tangxifan commented on .github/workflows/test.yml
>      - uses: actions/setup-python@v4
Please check the python version available on ubuntu 22.04. https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Now the min. version is 3.10+
Please update and check

2023-03-23 17:38 UTC, tangxifan commented on .github/scripts/install_dependencies.sh
> +    autoconf \
The packages from LINE8-59 are for the ``apt install``, while the ``requirements.txt`` are only for pip install.
So there is no need to move the lines.

2023-03-27 19:38 UTC, tangxifan commented on .github/scripts/hostsetup.sh
> +  g++-10 \
ctags -> exuberant-ctags 
python -> python2
qt5-default -> qtbase5-dev

2023-03-28 18:26 UTC, tangxifan commented on .github/scripts/install_dependencies.sh
>    clang-format-7 \
Delete 
- gcc/g++ 7
- gcc/g++ 8
- clang-6, clang-format-7

2023-03-28 18:29 UTC, tangxifan requested changes
After change the clang-format-7 to clang-format-12
Need to change the clang-format in cmake modules:

https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/99d71d90caf14b0711d3f04c25cd665e0abfabfb/cmake/modules/AutoClangFormat.cmake#L28

2023-03-28 18:36 UTC, tangxifan commented
Since ubuntu 22.04 do not have native packages of

- gcc/g++ -7
- gcc/g++ - 8
- clang-6
- clang-8
- clang-7-format

May consider to rework the build compatibility checks:

- Remove gcc-7, gcc-8, clang-6 and clang-8 support
- Add clang-10, clang-12 support

2023-03-28 18:39 UTC, tangxifan commented
May need to modify the build job matrix at:

https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/99d71d90caf14b0711d3f04c25cd665e0abfabfb/.github/workflows/test.yml#L363-L370

2023-03-29 05:04 UTC, tangxifan commented on .github/scripts/install_dependencies.sh
>    clang-10 \
![image](https://user-images.githubusercontent.com/11499826/228431798-92daeefa-c2e8-4055-bf81-39a1d441c6c9.png)

Please try to find the correct package name of clang-10

2023-03-29 23:41 UTC, tangxifan commented on .github/scripts/install_dependencies.sh
> +  clang-format-12 \
Add clang. Default clang version is v14

2023-03-30 17:50 UTC, tangxifan commented on .github/scripts/install_dependencies.sh
> +  tcl8.6-dev \
Regarding tcl errors, try to include the following packages

- https://packages.ubuntu.com/jammy/libtcl8.6

2023-03-30 17:59 UTC, tangxifan commented on .github/scripts/install_dependencies.sh
> +  clang-format-12 \
Now the supported clang-format under Ubuntu 22.04 is at least clang-format-11, while the default is clang-format-14

https://packages.ubuntu.com/search?suite=jammy&section=all&arch=any&keywords=clang-format&searchon=names

While we have hardcoded clang-format-7 in CMakelist:

https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/99d71d90caf14b0711d3f04c25cd665e0abfabfb/cmake/modules/AutoClangFormat.cmake#L28

2023-04-04 08:31 UTC, Tulong4Dev commented
Summary of Current Status:

What Have Been Done:
      1. Updated hostsetup.sh and install_dependencies.sh with modules required for Ubuntu 22.04 jammy; Where, gcc-7,8 and g++-7,8 had been dropped.
      2. Updated test.yml by targeting ubuntu:jammy, and dropped GCC 7,8 and g++-7,8 tests
      3. Update AutoClangFormat.cmake with clang-format-12

Latest Result:
      https://github.com/verilog-to-routing/vtr-verilog-to-routing/actions/runs/4567727210
           (same with latest: https://github.com/verilog-to-routing/vtr-verilog-to-routing/actions/runs/4600501945)
      1. QoR failure: There are a few QoR failures in nightly and strong test suites, which can be fixed by updating Golen Results in another PR;
      2. Code format issue: https://github.com/verilog-to-routing/vtr-verilog-to-routing/actions/runs/4567727210/jobs/8061874428, which needs an change to make-format.
      3. Clang-12 Failure: https://github.com/verilog-to-routing/vtr-verilog-to-routing/actions/runs/4567727210/jobs/8061880513, c++ compiler can't find proper header file for "std::swap" function to compile the source file; this one we can't reproduce it with local 22.04 machine, and have no clue on how to fix it. Henner could you please take a look? Really appreciate your help here.

Based current situation, we think to keep CI working is first priority, then we can follow up with other PRs to clean up issue and add back some compatibility supports.

@vaughnbetz @hzeller

2023-04-04 13:46 UTC, vaughnbetz commented
Agreed.  So do you recommend a merge now and fix the CI breaks shortly?

2023-04-05 00:49 UTC, tangxifan commented
> Agreed. So do you recommend a merge now and fix the CI breaks shortly?

Hi @vaughnbetz, yes we suggest merge it as critical CIs, such as build and regression tests are passing. We just need a few follow-up PRs to fix the code format, build compatibility and update QoR for some regression tests.

2023-04-05 01:03 UTC, merged

2023-04-05 01:04 UTC, vaughnbetz commented
Merging so CI keeps working. Thanks for the hard work on this one @Tulong4Dev and @tangxifan !  
Let me know if you need help fixing the remaining issues -- it is a high priority to get CI green again, since otherwise a lot of problems could creep in over the next days and weeks.