Modeling multi die stack [WIP]
verilog-to-routing/vtr-verilog-to-routing pull request #2259
Opened 2023-03-22 14:07 UTC by saaramahmoudi

#### Description
To support Multi-die FPGAs, we need to be able to support new xml tag called <layer>, each layer tag will specify a die. This PR will modify the XML parser to find these tags (default to 1 in case unspecified) and build a 3D or multi-die grid. The modification is backward compatible, hence existing architecture will not need to change. 

#### Related Issue
Further discussion of how we modify the XML file and parser is given on [issue ##2197](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2197).

#### Motivation and Context
Supporting Multi-die FPGAs in VPR.

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

2023-03-22 14:08 UTC, saaramahmoudi commented
@amin1377

2023-04-04 18:38 UTC, amin1377 commented
@vaughnbetz : As discussed, I changed the grid from a vector of 2D matrices to a 3D matrix.

2023-04-13 16:04 UTC, vaughnbetz requested changes
Looks good -- thanks for the accessors!

2023-04-23 18:52 UTC, amin1377 commented
@vaughnbetz : Your suggestions are applied, and this PR is ready to merge. [Here](https://utoronto-my.sharepoint.com/:x:/g/personal/amin_mohaghegh_mail_utoronto_ca/Ea5Sg1uCPJBKkEgv-eIDOaQBlNZ0tA9rpwAwuXeEWtRPnQ?e=J2hefC) is the QoR comparison for Titan and VTR benchmarks.

2023-04-25 20:26 UTC, vaughnbetz commented
I think this is now ready to be merged, so the WIP should be removed from the title.  Will come check before merging ...

2023-04-25 20:29 UTC, merged