RLPlace 2.0: Proposing block and move types
verilog-to-routing/vtr-verilog-to-routing pull request #2272
Opened 2023-04-06 02:08 UTC by saaramahmoudi

#### Description

In this PR, the RLPlace has been extended to propose both move and block type. Each action proposed by the agent is a pair of a move and a block type. 
The motivations behind this PR are:
1. Different block type might prefer different move types.
2. How frequent each block type needs to be moved throughout the anneal.
  
#### How Has This Been Tested?

Here is the [link](https://docs.google.com/spreadsheets/d/17A9B6hTdMkwPlwlMCMZB35XK9PEsVXOsf7bmm-2zSac/edit?usp=sharing) to results of titan_quick_qor and vtr_reg_qor_chain_large.

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

2023-04-06 02:09 UTC, saaramahmoudi commented
@vaughnbetz some of the golden results still needs to be updated. I will fix them after I get yosys to work. For now, I just made the PR to get the code reviewed.

2023-04-06 16:19 UTC, vaughnbetz reviewed
Partially reviewed ...

2023-04-06 16:19 UTC, vaughnbetz commented on vpr/src/place/RL_agent_util.cpp
> +                }
Take a look and see if some ifs can be collapsed with helper functions or variables you set and use later.

2023-04-06 16:19 UTC, vaughnbetz commented on vpr/src/place/directed_moves_util.cpp
> +                if (timing_weights && criticalities != NULL) {
Probably good to comment when criticalities are NULL (non-timing driven?)

2023-04-06 16:19 UTC, vaughnbetz commented on vpr/src/place/move_generator.h
> + * num_moves:      save the number of proposed moves of each move type(e.g. [0..NUM_PL_MOVE_TYPES-1])
I don't think you need to say "save" over and over again.  Just say 
"number of proposed moves of each move type (e.g. ..."

2023-04-06 16:19 UTC, vaughnbetz commented on vpr/src/place/move_generator.h
>   * @brief A Struct to hold statistics about the different move types
Holds statistics about the different move types performed so far in the placement.

2023-04-06 16:19 UTC, vaughnbetz commented on vpr/src/place/move_generator.h
> + * num_moves:      save the number of proposed moves of each move type(e.g. [0..NUM_PL_MOVE_TYPES-1])
1. As much as possible, get rid of some of this state, and just store everything over agent_available_types, and then post-process.  Less state to describe here, and less state to update in a cpu critical routine.

2. Longer term: explore having the 2nd state also have (block_type,move_type) but critical random and feasible region are special and don't pay attention to the block type. 

3. (If not removed) Rename num_moves: moves_per_move_type and aborted_moves.

2023-04-06 16:19 UTC, vaughnbetz commented on vpr/src/place/move_generator.h
> + * num_moves:      save the number of proposed moves of each move type(e.g. [0..NUM_PL_MOVE_TYPES-1])
Possibly lets you make a vector of a single structure (might be slightly easier to read).

2023-04-06 16:19 UTC, vaughnbetz commented on vpr/src/place/move_generator.h
> +     *  @param blk_type: function proposes a move with given block type if specified.
If -1, this function will choose the block randomly from the netlist, regardless of type.

2023-04-06 23:36 UTC, vaughnbetz requested changes
Looks good; some comments to address.

2023-04-06 23:36 UTC, vaughnbetz commented on vpr/src/place/simpleRL_move_generator.cpp
>      if (agent_info_file_) {
Helper function would be useful: if (agent_info_file_) .... call helper function.

2023-04-06 23:36 UTC, vaughnbetz commented on vpr/src/place/simpleRL_move_generator.cpp
>          auto itr = std::max_element(q_.begin(), q_.end());
Probably good to profile the code; see if we have any hot spots in functions like this.  This could be recoded to store the maximum element and the maximum value and you'd update it when the q table is updated. Only when the gain of the max element decreases do you need to scan them all.  But probably not worth the extra code, but profiling could be useful to see if any infrastructure.

2023-04-06 23:36 UTC, vaughnbetz commented on vpr/src/place/simpleRL_move_generator.cpp
>          auto itr = std::max_element(q_.begin(), q_.end());
Could also store in a binary tree if this is slow.

2023-04-06 23:36 UTC, vaughnbetz commented on vpr/src/place/simpleRL_move_generator.h
> +    size_t num_available_types_;            //Number of types that each arm of the karmed bandit problem can pull with
types -> block types

2023-04-06 23:36 UTC, vaughnbetz commented on vpr/src/place/simpleRL_move_generator.h
> +    size_t num_available_moves_;            //Number of arms of the karmed bandit problem (k)
Update: number of move types

2023-04-06 23:36 UTC, vaughnbetz commented on vpr/src/place/simpleRL_move_generator.h
>      void set_epsilon(float epsilon);
Comment these functions; can be short for this like set_epsilon

2023-04-06 23:36 UTC, vaughnbetz commented on vpr/src/place/simpleRL_move_generator.h
> +    void init_q_scores();
comment

2023-04-06 23:36 UTC, vaughnbetz commented on vpr/src/place/simpleRL_move_generator.h
> +    void set_block_ratio();
comment each function (all new ones for sure, existing if you know what they do). Can be short.

2023-04-06 23:36 UTC, vaughnbetz commented on vpr/src/place/simpleRL_move_generator.h
> +    std::vector<float> block_type_ratio_; //The probability of choosing each block type depends on its ratio in the netlist
[0..agent_block_types-1]; fraction of total netlist blocks of this type.

2023-04-25 20:17 UTC, vaughnbetz commented on vpr/src/place/move_utils.cpp
> +    //pick a random highly critical pin and find the nets driver block
@saaramahmoudi @MohamedElgammal : any thoughts?  If I'm right about this code, we should pull it into an issue.

2023-05-05 14:02 UTC, vaughnbetz commented
@saaramahmoudi : is this one ready to merge? If so, it would be good to do a final QoR check to test that all is well and attach it. Then I can merge it.

2023-05-05 14:04 UTC, saaramahmoudi commented
@vaughnbetz Ready to merge. Just need to confirm final QoR and execute make format. Both will be ready today.

2023-05-05 15:25 UTC, saaramahmoudi commented
@vaughnbetz place time and total runtime are higher in RL2 results. If you look at pack time, you will see the machine load difference. Hence, no QoR degradation after applying changes and debugging.
[Final QoR](https://docs.google.com/spreadsheets/d/1jd1k9tdeLWf5CEqk3OcXI_wU4mievk6UfCOX5U5IH90/edit?usp=sharing)

2023-05-08 12:44 UTC, saaramahmoudi commented
@vaughnbetz ready to be merged.

2023-05-08 20:13 UTC, merged