Fix Placer Seed Print
verilog-to-routing/vtr-verilog-to-routing pull request #2317
Opened 2023-05-17 20:04 UTC by saaramahmoudi

#### Description
Small PR; placer seed was always printed as 0 in vpr.out, since It was printed before It was set. Hence, the default value regardless of the command-line was printed. Set it before printing. 

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

2023-05-17 20:05 UTC, saaramahmoudi commented
@vaughnbetz

2023-05-18 17:49 UTC, saaramahmoudi commented
@vaughnbetz can you please publish your review so I can take actions?

2023-05-31 23:18 UTC, vaughnbetz commented on vpr/src/base/SetupVPR.cpp
> +    PlacerOpts->seed = Options.Seed;
@saaramahmoudi : placerOpts->seed setting line is now removed from the placer. If the two documentation updates can be made we can merge this. Or if that will take a while please create an issue to track them and I'll merge this.

2023-06-02 20:06 UTC, saaramahmoudi commented
@vaughnbetz The RLPlace command-line options are now added to the documentation. I also added NoC options to documentation since they weren't available either and fixed some traffic flow typos.

2023-06-02 21:43 UTC, vaughnbetz requested changes
Looks good, except for a few wording nits.  
Also, @Srivat97 has simultaneously been making a PR for NoC documentation so you'll need to sync up with him on that part.

2023-06-02 21:43 UTC, vaughnbetz commented on doc/src/vpr/command_line_usage.rst
> +
I know @Srivat97 has a PR that's about to land that documents the NoC options too. @Srivat97 : I suggest landing yours and then Sara can enhance any NoC documentation that doesn't capture everything she has here.

2023-06-02 21:43 UTC, vaughnbetz commented on doc/src/vpr/command_line_usage.rst
> +    taken to this exponent.Only impacts devices with different channel widths in
Add a space after "."

2023-06-02 21:43 UTC, vaughnbetz commented on doc/src/vpr/command_line_usage.rst
> +    It activates the RL agent placement instead of using fixed probability for each move type.
"a" fixed probability for each

2023-06-02 21:43 UTC, vaughnbetz commented on doc/src/vpr/command_line_usage.rst
> +    Enable multistate agent in the placement. A second state will be activated late in
"Enable a multistate agent during RL placement."  (first sentence).

2023-06-02 21:43 UTC, vaughnbetz commented on doc/src/vpr/command_line_usage.rst
> +    Placement RL agent's epsilon for epsilon-greedy agent. Epsilon represents
"for the epsilon-greedy agent."

2023-06-02 21:43 UTC, vaughnbetz commented on doc/src/vpr/command_line_usage.rst
> +    The reward function used by placement RL agent to learn best action at each anneal stage.
"by the placement RL agent to learn the best action"  (missing a couple of "the" )

2023-06-02 21:43 UTC, vaughnbetz commented on doc/src/vpr/command_line_usage.rst
> +    Agent exploration space can be either based on only move types or also consider different block types.
"The RL agent exploration space can either be based only on move types or can also consider the block type being moved."

2023-06-02 21:47 UTC, saaramahmoudi commented
> Looks good, except for a few wording nits. Also, @Srivat97 has simultaneously been making a PR for NoC documentation so you'll need to sync up with him on that part.

I don't see a PR from @Srivat97. Can you put the PR's name here and I can merge the branches and land both together?

2023-06-02 22:05 UTC, vaughnbetz commented
@Srivat97 : probably you haven't made a PR yet (@saaramahmoudi : Srivatsan showed me the documentation in our meeting today, but I don't see the PR either). Can you make a PR @Srivat97 ?

2023-06-08 17:53 UTC, saaramahmoudi commented
@vaughnbetz I just did a small clean-up on NoC router description in vpr.out, I moved printing of router connections in the architecture to echo file instead of printing 100 lines in the vpr.out. Could you please take a look at it to see if that sounds good to you?

2023-06-09 13:57 UTC, vaughnbetz commented
Looks good, thanks.  Will merge after talking to Srivatsan today.

2023-06-13 23:23 UTC, saaramahmoudi commented
@vaughnbetz ready to be merged.

2023-06-13 23:47 UTC, Srivat97 commented
@vaughnbetz , @saaramahmoudi : Sorry for the delayed response. You can go ahead and merge this PR first. I'll handle the conflicts on my end.

2023-06-14 01:16 UTC, merged