Updated graphics.rst (Documentation)
verilog-to-routing/vtr-verilog-to-routing pull request #2326
Opened 2023-05-29 20:21 UTC by Meet-Patel2580

Updated the documentation for VPR graphics by adding new images of the UI as well as fixing grammatical errors and descriptions of the locations of various buttons.

#### Description

#### Related Issue

#### Motivation and Context

#### How Has This Been Tested?

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2023-05-30 20:46 UTC, vaughnbetz requested changes

2023-05-30 20:46 UTC, vaughnbetz commented on doc/src/vpr/graphics.rst
> +The **Toggle Nets** drop-down list under the **Net Settings** tab toggles the nets in the circuit to be visible/invisible. Options include **Nets** and **Logical Connections**.
Look in the draw code to figure out what logical connections are and describe them here.  Send snippets of code to us by email if needed; can use git blame to see who added the logical connection lines in the menu.

2023-05-30 20:47 UTC, vaughnbetz commented
Looks good; one suggested change. Then ping me to merge.  Right after merging, check the web page to make sure all the images show up.

2023-06-06 21:00 UTC, vaughnbetz commented on doc/src/vpr/graphics.rst
> +The **Toggle Nets** drop-down list under the **Net Settings** tab toggles the nets in the circuit to be visible/invisible. Options include **Nets** and **Logical Connections**.
Logical nets should be renamed --> suggest Primitive nets
Nets should be renamed --> suggest Cluster nets
Help should explain that showing the primitive nets showing connections within the cluster, and the primitive within the cluster that drives/receives them.  Cluster nets shows only the nets that go between clusters.

2023-06-06 21:01 UTC, vaughnbetz commented
Another item to investigate (but should be another issue): can we show only the highlighted nets (fanin and fanout of selected block)?

2023-06-06 21:04 UTC, vaughnbetz commented
Should also change the code to have "Set Net Transparency" --> Net Transparency (0 - 255)

2023-06-13 14:49 UTC, Meet-Patel2580 commented
All suggested changes made. @vaughnbetz , You may now merge this PR, and I will check right after to make sure the images on the documentation are showing up properly.

2023-06-13 15:26 UTC, merged