Adding Encryption and Decryption Tool for XML
verilog-to-routing/vtr-verilog-to-routing pull request #2358
Opened 2023-08-01 06:36 UTC by umariqbal-rs

Adding a standalone tool to handle encrypted XML files.
For decryption, the decryption library is statically linked to libpugiutil to decrypting the XML.

2023-08-01 18:12 UTC, alaindargelas commented
@tangxifan , please add @umariqbal-rs as a contributor so his PR can trigger build Actions?
@manadherRS

2023-08-03 04:40 UTC, umariqbal-rs commented
@tangxifan

2023-08-07 21:21 UTC, tangxifan commented
@umariqbal-rs Can you try to resolve the merging conflicts and look into the CI errors ?

2023-08-08 07:30 UTC, umariqbal-rs commented
@ManadherRS FYI:
    I have updated my branch with the latest [commit](https://github.com/verilog-to-routing/vtr-verilog-to-routing/commit/f2783e2f8c7531d00fa3e857ee22d1c45f975815) of @tangxifan . And his commit is failing in CLI. Due to which our commit also fails.

2023-08-16 04:05 UTC, umariqbal-rs commented
@ManadherRS @tangxifan @alaindargelas  Please can you merge it.

2023-08-16 21:25 UTC, alaindargelas commented
Only @tangxifan can merge this PR.

2023-08-16 21:26 UTC, alaindargelas commented
@tangxifan , we plan to push this change to VPR master after it is merged in the openfpga branch.

2023-08-16 22:32 UTC, tangxifan commented
@alaindargelas Please give me 1 week to review the PR. Thanks!

2023-08-23 16:57 UTC, alaindargelas commented
@tangxifan , we are blocked with conflicts as long as this PR is not merged.
Can you approve it? It is harmless to the OpenFPGA functionality. It simply adds reading encrypted .xml files.

2023-08-23 18:14 UTC, tangxifan commented on libs/libencrypt/CMakeLists.txt
> +file(GLOB_RECURSE LIB_HEADERS src/*.hpp src/*.h  ../EXTERNAL/libpugixml/src/*.hpp)
You donot need to glob these files here. You can simply add the ``libpugixml`` to the ``target_linked_libraries``

For example, 

https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/ec634df07a5be186a0e7b66f2789c4daf2e4b44c/libs/librrgraph/CMakeLists.txt#L24-L28

2023-08-23 18:17 UTC, tangxifan requested changes
Looks good to me. Just some minor comments and we can merge.
Thanks!

2023-08-23 18:17 UTC, tangxifan commented on libs/libencrypt/config.h.in
> +
I suggest to move the config.h.in, config.txt, main.cpp to a subdirectory ``test``. Following the convention as other vtr library: 

https://github.com/verilog-to-routing/vtr-verilog-to-routing/tree/ec634df07a5be186a0e7b66f2789c4daf2e4b44c/libs/libvtrutil

2023-08-23 18:20 UTC, umariqbal-rs commented
Hi xifan , Because Encryption is standalone here. We are not linking it with complete VTR flow and vpr.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: tangxifan ***@***.***>
Sent: Wednesday, August 23, 2023 11:18:11 PM
To: verilog-to-routing/vtr-verilog-to-routing ***@***.***>
Cc: Umar Iqbal ***@***.***>; Mention ***@***.***>
Subject: Re: [verilog-to-routing/vtr-verilog-to-routing] Adding Encryption and Decryption Tool for XML (PR #2358)


@tangxifan requested changes on this pull request.

Looks good to me. Just some minor comments and we can merge.
Thanks!

________________________________

In libs/libencrypt/config.h.in<https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/2358#discussion_r1303383447>:

> @@ -0,0 +1,9 @@
+


I suggest to move the config.h.in, config.txt, main.cpp to a subdirectory test. Following the convention as other vtr library:

https://github.com/verilog-to-routing/vtr-verilog-to-routing/tree/ec634df07a5be186a0e7b66f2789c4daf2e4b44c/libs/libvtrutil

—
Reply to this email directly, view it on GitHub<https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/2358#pullrequestreview-1592162118>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVLZU6NQUQIJVS4SEZTMX4TXWZCOHANCNFSM6AAAAAA27IRBO4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-08-23 18:24 UTC, umariqbal-rs commented
We are not linking encryption with complete flow. We are just linking decryption library in complete VTR flow. That is why I used glob rescue here.
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: tangxifan ***@***.***>
Sent: Wednesday, August 23, 2023 11:15:08 PM
To: verilog-to-routing/vtr-verilog-to-routing ***@***.***>
Cc: Umar Iqbal ***@***.***>; Mention ***@***.***>
Subject: Re: [verilog-to-routing/vtr-verilog-to-routing] Adding Encryption and Decryption Tool for XML (PR #2358)


@tangxifan commented on this pull request.

________________________________

In libs/libencrypt/CMakeLists.txt<https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/2358#discussion_r1303380918>:

> +#string(REPLACE "\n" "\\n" PUBLIC_KEY_CONTENTS "${PUBLIC_KEY_CONTENTS}")
+string(REPLACE "\n" "\\n" PASSPHRASE_CONTENTS "${PASSPHRASE_CONTENTS}")
+#set(PUBLIC_KEY "${PUBLIC_KEY_CONTENTS}")
+set(PASS_PHRASE "${PASSPHRASE_CONTENTS}")
+add_compile_definitions(PASS_PHRASE="${PASS_PHRASE}")
+
+if(OPENSSL_FOUND)
+    include_directories(${OPENSSL_INCLUDE_DIRS})
+    message(STATUS "Using OpenSSL ${OPENSSL_VERSION}")
+else()
+    message(FATAL_ERROR "OpenSSL not found")
+endif()
+
+# Source files for the library
+file(GLOB_RECURSE LIB_SOURCES src/*.cpp ../EXTERNAL/libpugixml/src/*.cpp)
+file(GLOB_RECURSE LIB_HEADERS src/*.hpp src/*.h  ../EXTERNAL/libpugixml/src/*.hpp)


You donot need to glob these files here. You can simply add the libpugixml to the target_linked_libraries

For example,

https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/ec634df07a5be186a0e7b66f2789c4daf2e4b44c/libs/librrgraph/CMakeLists.txt#L24-L28

—
Reply to this email directly, view it on GitHub<https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/2358#pullrequestreview-1592157823>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVLZU6PFTNN6XEGCP4CCPZDXWZCCZANCNFSM6AAAAAA27IRBO4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-08-23 18:43 UTC, tangxifan commented
@umariqbal-rs 

Can you provide more details about 

```
We are not linking encryption with complete flow. We are just linking decryption library in complete VTR flow.
```

I am not sure what is the definition of complete flow. In my view, VTR flow is a complete flow. If you use hard coded paths in CMakeLists.txt, more maintanance is required if someone changes the file organization of libpugixml. In either way, i.e., glob or target_linked_library, it will not change the fact that your library is loosely integrated with VPR

2023-08-23 18:53 UTC, alaindargelas commented
@umariqbal-rs create a library target that only uses the files required to be linked for the decrypt part.
And another library target for the encrypt part.
Use the decrypt target to link with VPR.

2023-08-24 11:42 UTC, umariqbal-rs commented
@alaindargelas @tangxifan  Can you please review now .

2023-08-24 11:43 UTC, umariqbal-rs commented
@tangxifan I have updated branch and nightly test is failing because main branch nightly test are failing as well.

2023-08-24 17:00 UTC, tangxifan approved these changes

2023-08-24 17:10 UTC, umariqbal-rs commented
Hi Xifan our changes do not make any difference in VTR flow. As we can see the latest main branch has failure in regression tests as well that why our tests are failing because we updated Branch. I think you can merge. @Alain ***@***.***> can you please comment here. We are adding just linking a decryption library.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: tangxifan ***@***.***>
Sent: Thursday, August 24, 2023 10:01:48 PM
To: verilog-to-routing/vtr-verilog-to-routing ***@***.***>
Cc: Umar Iqbal ***@***.***>; Mention ***@***.***>
Subject: Re: [verilog-to-routing/vtr-verilog-to-routing] Adding Encryption and Decryption Tool for XML (PR #2358)


@umariqbal-rs<https://github.com/umariqbal-rs> Please try a local run on the failed regression tests. If you see no failures, we can merge then.

—
Reply to this email directly, view it on GitHub<https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/2358#issuecomment-1692094182>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVLZU6JABO2ZIW6HT257K6DXW6CHZANCNFSM6AAAAAA27IRBO4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-08-24 17:28 UTC, alaindargelas commented
@umariqbal-rs , it does not matter what functionality we are adding, we need to see **all tests** passing.
Please, as @tangxifan requested, relaunch the failed actions in Github (There is a Rerun button in the Action section). And/or run those failed tests locally on your machine and make sure they pass before we can merge.

2023-08-27 17:21 UTC, umariqbal-rs commented
@tangxifan @ManadherRS @tangxifan Finally CI is green . Can you merge please.

2023-08-27 17:56 UTC, merged