Bug fixes
verilog-to-routing/vtr-verilog-to-routing pull request #2380
Opened 2023-08-30 18:54 UTC by Meet-Patel2580

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-08-30 19:36 UTC, vaughnbetz requested changes
A couple of changes to consider.

2023-08-30 19:36 UTC, vaughnbetz commented on vpr/src/draw/draw.cpp
>  static void highlight_blocks(double x, double y) {
1. Put a comment on what this function does in the .h file.  It highlights the block that was clicked on, looking from the top layer downwards for 3D devices (choose the top visible layer for overlapping blocks). It highlights the block, its fanin and fanout, in various colours by updating the draw_state variables.

2. Could consider factoring this routine to have a helper function that returns the blk_id (or -1) of the clicked on block.  That would shorten this function by moving the top part to another routine, and make commenting it easier.

2023-09-03 22:56 UTC, Meet-Patel2580 commented on vpr/src/draw/draw_rr.cpp
highlighting of RR nodes has just been changed to ensure that only nodes on currently visible layers are checked to determine whether they should be highlighted or not. This fixes the bug of the user clicking on a node, but not seeing it highlight due to the code mistakenly changing the highlight setting for a node on an invisible layer.

2023-09-06 15:34 UTC, vaughnbetz reviewed
One suggested comment update. Can update that before or after merge, based on whatever is more convenient.

2023-09-06 15:34 UTC, vaughnbetz commented on vpr/src/draw/draw.h
> + * @param x
Say in world coordinates (for both x and y)

2023-09-07 15:07 UTC, vaughnbetz commented
@Meet-Patel2580 : are the clicked x,y coordinates in world coordinates?  If so we should comment that; I think after that it can be merged.

2023-09-10 18:29 UTC, vaughnbetz commented
Looks good; can be merged as soon as CI finishes.

2023-09-11 21:09 UTC, merged