[WIP] Placement Debug Messages
verilog-to-routing/vtr-verilog-to-routing pull request #2389
Opened 2023-09-11 16:09 UTC by amin1377

In this pull request (PR), we've made some enhancements related to debugging messages in placement, aligning them with those found in the router. These additional details are printed only when the `VTR_ENABLE_DEBUG_LOGGING` option is enabled.

Two new command-line arguments, "--placer_debug_net" and "--placer_debug_block" are added. When either of them is set to "-1," the placer will output debug information concerning all blocks and nets. If the value is greater than or equal to zero, the placer will print information when the moving block matches the specified block ID or when one of the connections of the given net id is connected to the block being considered for movement.

2023-09-12 18:36 UTC, amin1377 commented
@vaughnbetz I think this PR is ready to merge

2023-09-12 19:39 UTC, vaughnbetz requested changes
I'd like to get rid of the naked global variable; prefer putting it in an existing context.
Global variables and structure members should also be commented.

Finally, just to be safe please run at least one circuit with default compile / cmake settings and confirm no slowdown.  There shouldn't be any since the logging is conditionally compiled, but it is best to always be paranoid and check.

2023-09-12 19:39 UTC, vaughnbetz commented on vpr/src/base/vpr_types.h
> +    int placer_debug_block;
Please add a brief comment for each of these; it can refer to the command line parser help for more detail if you want to avoid duplication.

2023-09-12 19:39 UTC, vaughnbetz commented on vpr/src/place/move_utils.cpp
> +bool f_placer_debug = false;
Comment this variable.

2023-09-12 19:39 UTC, vaughnbetz commented on vpr/src/place/move_utils.h
> +extern bool f_placer_debug;
1. Comment.
2. Why not put this in the placement context or placer opts?  We're trying to get away from naked global variables.

2023-09-14 16:10 UTC, vaughnbetz commented
In this CI, it seems the tests that ran on github runners worked, but all the google cloud ones failed with this message:

Error: Failed to resolve action download info.

If this is still happening please file an issue ASAP and we'll discuss in the vtr meeting today.  If we need something from Google, we can ask Herman in the meeting.

2023-09-14 16:21 UTC, vaughnbetz requested changes

2023-09-14 16:21 UTC, vaughnbetz commented on vpr/src/place/initial_placement.cpp
> +            const auto& cluster_blk_pb_type = cluster_ctx.clb_nlist.block_type(blk_id)->pb_type;
1. This should be a subroutine I think (cleaner, less cognitive pollution for the main code path).
2. It should be guarded by your #ifdef VTR_ENABLE_DEBUG_LOGGING

2023-09-14 16:21 UTC, vaughnbetz commented on vpr/src/place/move_utils.cpp
> +    if (b_from) {
This should be a subroutine I think (cleaner, less cognitive pollution for the main code path).
It should be guarded by your #ifdef VTR_ENABLE_DEBUG_LOGGING

2023-09-14 16:22 UTC, vaughnbetz commented
If the router debug messages are similar, they should also be refactored to use a helper function and have conditional compilation guards.

2023-09-14 16:23 UTC, vaughnbetz commented
@amin1377 tells me the router code is not in an inner loop so we can leave it alone.

2023-09-15 14:10 UTC, amin1377 commented
I tested this PR on the VTR large benchmarks. The QoR was exactly the same, and the run times were less ~1% different.

2023-09-15 14:57 UTC, vaughnbetz requested changes
#ifndef looks backwards.
Needs a comment on the new helper routine.

2023-09-15 14:57 UTC, vaughnbetz commented on vpr/src/place/initial_placement.cpp
> +#ifndef VTR_ENABLE_DEBUG_LOGGING
Shouldn't this be #ifdef?

2023-09-15 14:57 UTC, vaughnbetz commented on vpr/src/place/move_utils.cpp
> +#ifndef VTR_ENABLE_DEBUG_LOGGING
Shouldn't this be #ifdef?

2023-09-15 14:57 UTC, vaughnbetz commented on vpr/src/place/move_utils.cpp
> +#ifndef VTR_ENABLE_DEBUG_LOGGING
#ifdef

2023-09-15 14:57 UTC, vaughnbetz commented on vpr/src/place/move_utils.h
> +#ifndef VTR_ENABLE_DEBUG_LOGGING
1. Should be #ifdef, not $ifndef
2. Needs a comment saying what the routine does.

2023-09-15 15:24 UTC, amin1377 commented
> #ifndef looks backwards. Needs a comment on the new helper routine.

You are right. It should be #ifdef. Apparently, it didn't have the run-time effect that I thought it had!

2023-09-15 15:34 UTC, vaughnbetz commented on vpr/src/place/move_utils.h
> + * @param blk_id The if of the block that is considered to be moved
if -> id

2023-09-16 15:13 UTC, amin1377 commented
@vaughnbetz CIs are green

2023-09-16 22:10 UTC, merged