Improved parallel router: add NetlistRouter and refactor code
verilog-to-routing/vtr-verilog-to-routing pull request #2411
Opened 2023-10-06 01:24 UTC by duck2

This adds a common `NetlistRouter` interface for the serial and parallel routers and removes the code duplication between `route_timing.cpp` and `route_parallel.cpp`. `route_timing.cpp` is divided into three files `route_net.cpp`, `route_utils.cpp` and `route.cpp`. Top-level `route()` no longer manages a `ConnectionRouter`, so it doesn't need to be templated.

`ConnectionRouter` no longer retries with a full-device bounding box by itself. The "retry with full BB" flag is bubbled up and it's up to the NetlistRouter to retry the connection/net properly.

Will experiment with high-fanout behavior in `ConnectionRouter` and whether clipping HF BBs hurts QoR in the serial case. It's mandatory in the parallel case.

#### How Has This Been Tested?
* CI tests
* Will attach QoR from Titan & VTR

#### Types of changes
- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2023-10-07 02:24 UTC, duck2 commented
It looks like there's a single `min_chan_width_route_time` failure and a segfault in a unit test... no idea why. Can update the golden result for the first failure, since that can vary wildly. Waiting for initial titan results.

2023-10-07 13:01 UTC, duck2 commented
`titan_quick_qor`, serial routing, placement seed=10 (both runs did placement to make sure we didn't break it): 
[titan_10_t1.xlsx](https://github.com/verilog-to-routing/vtr-verilog-to-routing/files/12837840/titan_10_t1.xlsx)

**Metric**|**15c5340**|**This**
:-----:|:-----:|:-----:
max\_vpr\_mem|1|1.000
pack\_time|1|0.991
placed\_wirelength\_est|1|1.000
place\_time|1|1.001
placed\_CPD\_est|1|1.000
routed\_wirelength|1|1.000
critical\_path\_delay|1|0.990
geomean\_nonvirtual\_intradomain\_critical\_path\_delay|1|0.992
crit\_path\_route\_time|1|1.014

2023-10-07 17:44 UTC, duck2 commented
Nightly koios, extracted from GH runners. No .xlsx file -- had to manually get the data from the artifacts because it looks like the parser isn't doing its job. Koios runs are fixed chan width, so they should be parsed by something like vpr_titan.txt, not vpr_standard.txt.

Circuit| Runtime (8e59d59) |This|Ratio| CPD (8e59d59) |This|Ratio
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
bwave\_like.float.small.v|98.37|98.06|0.997|7.849|7.563|0.964
dnnweaver.v|91.02|124.54|1.368|10.287|11.632|1.131
tdarknet\_like.small.v|85.81|82.670|0.963|19.866|17.566|0.884
proxy.5.v|23.60|23.06|0.977|8.712|8.712|1.000
proxy.7.v|45.94|46.25|1.007|9.053|9.079|1.003
proxy.8.v|24.04|24.63|1.025|8.632|8.632|1.000
Geomean| | |1.048| | |0.994

2023-10-07 19:01 UTC, duck2 commented
VTR benchmarks extracted from GH runners: [vtr_gh_t1.xlsx](https://github.com/verilog-to-routing/vtr-verilog-to-routing/files/12838544/vtr_gh_t1.xlsx)

**circuit**|**Runtime (8e59d59)**|**This**|**Ratio**|**CPD (8e59d59)**|**This**|**Ratio**|**WL (8e59d59)**|**This**|**Ratio**|**W\_min (8e59d59)**|**This**|**Ratio**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
arm\_core.v|13.94|14.95|1.072|22.914|22.914|1.000|184307|184307|1.000|116|116|1.000
bgm.v|15.43|9.88|0.640|20.283|20.283|1.000|402334|402334|1.000|74|74|1.000
stereovision1.v|9.31|9.1|0.977|5.441|5.441|1.000|131011|131011|1.000|88|88|1.000
stereovision2.v|17.92|18.57|1.036|13.719|13.719|1.000|422372|422372|1.000|96|96|1.000
LU8PEEng.v|20.18|21.8|1.080|74.240|74.240|1.000|340308|340308|1.000|96|96|1.000
LU32PEEng.v|81.52|83.43|1.023|73.170|73.170|1.000|1348522|1348522|1.000|132|132|1.000
mcml.v|36.91|36.71|0.995|45.477|45.456|1.000|999026|997319|0.998|142|144|1.014
Geomean| | |0.962| | |1.000| | |1.000| | |1.002

2023-10-23 17:15 UTC, vaughnbetz requested changes
Commenting changes and moving functions around.
QoR looks good; once these updates are made it's good to merge.

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_net.tpp
> +inline NetResultFlags try_timing_driven_route_net(ConnectionRouter& router,
Comment what this routine does (and how is it different than timing_driven_route_net).  Or just merge them (you say merging is your plan).

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_net.tpp
> +inline NetResultFlags timing_driven_pre_route_to_clock_root(ConnectionRouter& router,
Comment this if you can.

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_net.tpp
> +inline NetResultFlags timing_driven_pre_route_to_clock_root(ConnectionRouter& router,
It routes to a special sink that is not in the netlist, and which represents the start point of a global clock network.

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_net.cpp
> +/** Change the base costs of rr_nodes according to # of fanouts */
See if this comment should be in the .h file.

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_net.cpp
> +bool should_route_net(ParentNetId net_id,
Comment should be in .h file

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_net.cpp
> +bool is_high_fanout(int fanout, int fanout_threshold) {
Comment should be in .h file

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_net.cpp
> +t_bb calc_current_bb(const RouteTree& tree) {
Comment should be in .h file

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_net.cpp
> +bool early_reconvergence_exit_heuristic(const t_router_opts& router_opts,
Comment should be in .h file

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_net.cpp
> +bool early_reconvergence_exit_heuristic(const t_router_opts& router_opts,
Fahri: should go in route_utils.

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_net.cpp
> +void update_net_delays_from_route_tree(float* net_delay,
Comment should be in .h file

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_utils.h
> +bool early_reconvergence_exit_heuristic(const t_router_opts& router_opts,
Move implementation to route_utils.cpp

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_utils.h
> +int get_max_pins_per_net(const Netlist<>& net_list);
Add comments to any routines in here where you know what they do.

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_utils.h
> +float update_pres_fac(float new_pres_fac);
Comment

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_utils.cpp
> +size_t dynamic_update_bounding_boxes(const std::vector<ParentNetId>& updated_nets) {
Make sure there is a reasonable comment in the .h file too; could move this there or do a more brief .h comment.

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_utils.cpp
> +    //This function checks if a routing iteration has completed.
Move some or all of this comment to the .h

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_utils.cpp
> +void prune_unused_non_configurable_nets(CBRR& connections_inf,
Move comment to header.

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_utils.cpp
> +float update_pres_fac(float new_pres_fac) {
Move comment to .h file.

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/route_utils.cpp
> +float update_pres_fac(float new_pres_fac) {
Rename to update_pres_fac_for_draw

2023-10-23 17:15 UTC, vaughnbetz commented on vpr/src/route/router_stats.h
> +    void combine(RouterStats& rhs) {
Comment this.

2023-11-13 16:37 UTC, vaughnbetz commented
@duck2: is this ready to merge?  
- there was a unit test seg fault --> resolved?
- serial QoR looks good.
- Any need to test parallel QoR, or just merge and test later?

2023-11-13 18:24 UTC, vaughnbetz commented
@soheilshahrouz : the unit test failure is a NoC test that removes and adds a link (it seg faults).  It's hard to see how Fahri's code could cause that so I suspect it's a pre-existing weakness.  Can you take a look?

2023-11-13 21:01 UTC, soheilshahrouz commented
> @soheilshahrouz : the unit test failure is a NoC test that removes and adds a link (it seg faults). It's hard to see how Fahri's code could cause that so I suspect it's a pre-existing weakness. Can you take a look?

Is this test failure different than the one mentioned in the link below?
https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/2357#issuecomment-1690534663

2023-11-14 00:00 UTC, vaughnbetz commented
Not sure.  @ducks2?

2023-11-14 23:41 UTC, merged