Fix Inter-Die Connection Delay on SIV-Like Architecture
verilog-to-routing/vtr-verilog-to-routing pull request #2490
Opened 2024-02-19 20:13 UTC by amin1377

Add the scaled delay from the "koios_3d" benchmark into the 3D SIV-like architecture. The inter-die delay is calculated by multiplying the delay of the L4 segment by the ratio of the inter-die delay to the L4 delay of the Koios_3D architecture.

2024-03-04 21:08 UTC, amin1377 commented
2D Titan: 
![Screenshot from 2024-03-04 16-08-26](https://github.com/verilog-to-routing/vtr-verilog-to-routing/assets/44939647/23260915-29bf-47c5-b350-fb977aa0f82f)

2024-03-07 17:26 UTC, vaughnbetz commented
Add 3D results.

2024-03-07 17:44 UTC, vaughnbetz requested changes
A few changes suggested, and please get the 3D data.

2024-03-07 17:44 UTC, vaughnbetz commented on vpr/src/place/centroid_move_generator.cpp
> +    // layer for the centroid location. So if the layer is not valid, we set it to the same layer as from loc.
expect -> expects

2024-03-07 17:44 UTC, vaughnbetz commented on vpr/src/place/median_move_generator.cpp
> +            if (!get_bb_incrementally(net_id,
Make a comment of why this works.

2024-03-07 17:44 UTC, vaughnbetz commented on vpr/src/place/place.cpp
> +    VTR_ASSERT(layer_min >= 0 && layer_min < device_ctx.grid.get_num_layers());
might make this a VTR_ASSERT_DEBUG (reasonably hot function).

2024-03-07 17:44 UTC, vaughnbetz commented on vpr/src/place/placer_context.h
>      std::vector<int> X_coord;
Could experiment with the speed of a array of structs (t_pos I think).

2024-03-07 17:44 UTC, vaughnbetz commented on vpr/src/place/placer_context.h
>      std::vector<int> X_coord;
OK, scratch that as you have to sort them.  But comment that (reason why we use independent vectors).

2024-03-07 17:44 UTC, vaughnbetz commented on vtr_flow/arch/multi_die/stratixiv_3d/3d_full_OPIN_inter_die_stratixiv_arch.timing.xml
> +    <switch type="mux" name="seg4_inter_layer_driver" R="0.0" Cin="0.0" Cout="0.0" Tdel="138.82e-12" mux_trans_size="2.630740" buf_size="27.645901"/>
Could comment why this delay is what it is (reasoning behind taking it from Koios).

2024-05-16 19:15 UTC, vaughnbetz commented
@amin1377 : is this one ready to merge?

2024-05-22 21:07 UTC, amin1377 commented
@vaughnbetz: I've just added more comments and rebased it with the master branch. Once the CI tests pass successfully, it'll be ready for merging.

2024-05-30 12:04 UTC, merged