NoC-aware packing optimization and NoC-biased centroid move type
verilog-to-routing/vtr-verilog-to-routing pull request #2546
Opened 2024-04-29 21:20 UTC by soheilshahrouz

The packing algorithm may infer logical connectivity through high-fanout nets like reset and clock enable, especially in NoC designs. This could lead to atoms from unconnected modules being packed together. Once this happens, more atoms from the unconnected module can join through low-fanout nets. Placing such clustered blocks is challenging because they are connected (not necessarily directly) to NoC routers, but NoC routers are usually very far from each other. As a results, clustered blocks of two unconnected modules are stretched between two NoC routers. To address this, we use BFS on the atom netlist to identify connected components including NoC routers. Once identified, we prevent atoms from different components from clustering together.

In the placement stage, a new move type is introcuded: NoC-baised centroid. After the centroid loaction of a clustered block is computed, it is adjusted towards its reachable NoC routers. To find reachable NoC routers for all blocks, we run BFS on the clustered netlist to find connected components containing NoC routers.

This PR is submitted for code review. QoR results for the initial implementation of this PR are available in the paper. QoR results for the current version will be added soon.

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2024-05-14 00:50 UTC, vaughnbetz requested changes
Some requested changes, mostly (all?) commenting and naming.

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/pack/cluster_util.h
> +
Doxygen comment?

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/pack/cluster_util.h
> +bool atom_cluster_floorplanning_check(AtomBlockId blk_id,
I know this one isn't yours, but it would be good to add a Doxygen comment if you know its functionality.

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/pack/noc_aware_cluster_util.h
> +#ifndef VTR_NOC_AWARE_CLUSTER_UTIL_H
Comment purpose of overall file. This would be a logical place for a high-level comment on the whole algorithm / idea and a ref to the FPL paper.

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/pack/noc_aware_cluster_util.h
> +std::vector<AtomBlockId> find_noc_router_atoms();
Comment both these routines with Doxygen comments.

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/pack/noc_aware_cluster_util.cpp
> +    for (auto noc_atom_id : noc_atoms) {
Comment what you are doing here.  A breadth first search reachability analysis starting at each router, that follows input and output nets below the high_fanout_threshold, and marks each netlist block with a count indicating which cluster (NoC group) it was reached from. Atoms are only labelled once, by the first breadth first search that finds them.

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/place/centroid_move_generator.cpp
> +    noc_group_clusters_.clear();
I think this long constructor code would be better moved to a helper function with a descriptive name.

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/place/centroid_move_generator.h
> +    CentroidMoveGenerator(float noc_attraction_weight, size_t high_fanout_net);
Comment constructors and parameters. First is for a regular CentroidMoveGenerator (only considers netlist connections), while the second is NoC-biased with parameters ...

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/place/centroid_move_generator.h
> +    /** Stores all non-router blocks for each NoC group*/
"the ids of all cluster-level blocks ..."

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/place/centroid_move_generator.h
> +    static const std::vector<ClusterBlockId>& get_noc_group_routers(NocGroupId noc_grp_id);
Useful to have short Doxygen comments even for these accessors, as they'll show up as tooltips in IDEs and it makes the Doxygen html complete.

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/place/directed_moves_util.h
>   *      @return The calculated location is returned in centroid parameter that is sent by reference
Update the comment to include the new parameters.

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/place/move_utils.cpp
> +int has_empty_compatible_subtile(t_logical_block_type_ptr type, const t_physical_tile_loc& to_loc) {
This is now returning a subtile number (not just a bool for there is a compatible subtile or not) so you should change the function name to indicate it. Also make sure the header file comment is updated.

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/place/move_utils.h
>   * @return bool True if the given location has at least one empty compatible subtile.
Comment is out of date, and function name is misleading.

2024-05-14 00:50 UTC, vaughnbetz commented on vpr/src/util/vpr_utils.cpp
> +static constexpr size_t MAX_STRING_LEN = 128;
We should probably make this bigger ... 128 is a bit limiting / risky!  I suggest at least 512 characters.

2024-05-22 23:37 UTC, soheilshahrouz commented
@vaughnbetz
I added more comments and a few subroutines based on your review.

2024-05-23 19:17 UTC, merged