add pin counting filter option to pack_mol_in_existing_cluster
verilog-to-routing/vtr-verilog-to-routing pull request #2585
Opened 2024-06-05 00:47 UTC by KA7E

Added enable_pin_feasibility_filter parameter to pack_mol_in_existing_cluster

#### Description

#### Related Issue

#### Motivation and Context

#### How Has This Been Tested?

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2024-06-05 16:38 UTC, AlexandreSinger commented
<img width="1439" alt="image" src="https://github.com/verilog-to-routing/vtr-verilog-to-routing/assets/49374526/65f229d5-4cef-4e61-872c-6cc6b6b6fa3f">

Thats not a good error to see. It looks like our self-hosted machines are not having a great time. One issue for this @KA7E is that the CI is run on EVERY push AND PR raised on a branch. If you are not careful you may be running the CI way more often than you think. This appears to be causing strain on the machines. We may have to wait for the CI to calm down a bit.

I am currently working on getting having the CI get called less and save less information so this is more unlikely to happen. But for now, lets get the other PRs merged in.

2024-06-07 00:46 UTC, AlexandreSinger commented
<img width="1428" alt="image" src="https://github.com/verilog-to-routing/vtr-verilog-to-routing/assets/49374526/fbc28735-7d0a-4a40-9427-3987658f27d8">

This error pretty clearly has nothing to do with your changes (since this actually ran the CI twice and one of them passed). @vaughnbetz , I wonder if this is caused by the artifacts thing we were talking about earlier this week.

Like this does not look good LOL:
<img width="846" alt="image" src="https://github.com/verilog-to-routing/vtr-verilog-to-routing/assets/49374526/ff9a6658-0159-42d3-9f59-284cb7e2747c">

But granted I have always seen it over, but usually its only 30 GB not 140 GB. However, reading into it this is actually from CCache not from artifacts:
<img width="766" alt="image" src="https://github.com/verilog-to-routing/vtr-verilog-to-routing/assets/49374526/0d527ed9-78ad-4411-a0e8-e9ec6ac6193e">

Either way I will look into how we are storing caches and think about how we can reduce it, since it looks like we are storing 400 MB of data per cache which feels like a lot.

Regarding the artifacts thing though, this is either a fluke; or we are having issues with how much artifacts we can store. @vaughnbetz maybe we can follow the steps to reduce the storage from 90 days to 45 days.

2024-06-07 18:06 UTC, AlexandreSinger commented
@KA7E I have merged in master, which contains my fix to the CI. I wanted to use this branch as a guinea pig, since every time you push it actually used to run the CI twice. Now with these changes it only runs the CI once. Mission success lol.

The CI is much calmer this morning (especially after I killed a bunch of duplicate runs), so hopefully this should pass without issue. The CI should become much more stable as more people merge in my recent PR.

2024-06-07 18:34 UTC, vaughnbetz requested changes

2024-06-07 18:34 UTC, vaughnbetz commented on vpr/src/pack/re_cluster_util.h
> +                                  bool enable_pin_feasibility_filter = true);
Add a doxygen comment explaining enable_pin_feasibility_filter (new @param ...)

2024-06-10 19:36 UTC, vaughnbetz commented
Looks good. For safety, I'd like to get at least one design (e.g. neuron) with a CPU time number before and after the various related PR changes to confirm CPU time in the default flow is unaffected.  
That could be done with a QoR sweep but a simpler test that would also work would just be to run one design on a machine with controlled load (e.g. your machine) and post the pack & place & total run times, along with post-route cpd and wirelength.  I don't expect any changes, but it pays to be paranoid as it is very, very hard to find a degradation that slips into the master branch.

2024-06-11 20:40 UTC, merged