Removing warnings from libencrypt and libdecrypt
verilog-to-routing/vtr-verilog-to-routing pull request #2629
Opened 2024-06-25 12:38 UTC by behzadmehmood-rs

#### Description

This change simply removes warnings due to type casting.

#### Related Issue

#### Motivation and Context

It is necessary for a warning free CI.

#### How Has This Been Tested?

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2024-07-09 04:01 UTC, behzadmehmood-rs commented
@tangxifan some QoR tests are failing in CI which are not related to the changes in this PR.

2024-07-09 04:07 UTC, tangxifan commented
@behzadmehmood-rs Thanks. The CI failures are expected then. Good job.

2024-07-09 04:08 UTC, tangxifan commented
@Tulong4Dev Please help on reviewing this PR.

2024-07-09 05:32 UTC, Tulong4Dev requested changes
did a quick screening and suggested to make some minor fix.
 meanwhile, i'm afraid there could be some memory leakage which i suggest to use valgrind to detect and verify it, if possible.

2024-07-09 05:32 UTC, Tulong4Dev commented on libs/libencrypt/src/encryption.cpp
> +        return -1;
should return a Boolean  here.

2024-07-09 05:32 UTC, Tulong4Dev commented on libs/libencrypt/src/encryption.cpp
> +    unsigned char sessionKey[16];
can we avoid using constant number here ("16") directly?  we can use a meaningful constant variable to represent it.

2024-07-09 06:36 UTC, behzadmehmood commented
> did a quick screening and suggested to make some minor fix. meanwhile, i'm afraid there could be some memory leakage which i suggest to use valgrind to detect and verify it, if possible.

I have made the changes, now I will run it with valgrind.

2024-07-09 07:16 UTC, behzadmehmood commented
> > did a quick screening and suggested to make some minor fix. meanwhile, i'm afraid there could be some memory leakage which i suggest to use valgrind to detect and verify it, if possible.
> 
> I have made the changes, now I will run it with valgrind.

@Tulong4Dev , I have also updated the code to avoid memory leaks.

2024-07-10 01:24 UTC, Tulong4Dev reviewed
LGTM. In addition, I'd suggest to add a test with encrypt/decrypt so VTR's Valgrind test flow could help to detect potential memory leak.

2024-07-10 04:19 UTC, behzadmehmood commented
> LGTM. In addition, I'd suggest to add a test with encrypt/decrypt so VTR's Valgrind test flow could help to detect potential memory leak.

Is it okay to put the test data and code in `libdecrypt`?

2024-07-10 14:00 UTC, behzadmehmood commented
> LGTM. In addition, I'd suggest to add a test with encrypt/decrypt so VTR's Valgrind test flow could help to detect potential memory leak.

@Tulong4Dev I have added a test but I could not update workflow file properly. Can you please suggest how should I run the test?

2024-07-21 13:14 UTC, tangxifan commented on libs/libdecrypt/test/src/test.cpp
> +void createTestXMLFile(const std::string& filePath) {
@Tulong4Dev Please check if the test provided is sufficient. If a local run on the unit test is o.k., I suggest to merge this PR. This PR is currently a blocking factor on another PR #2637

2024-07-30 05:01 UTC, tangxifan approved these changes

2024-07-30 05:01 UTC, Tulong4Dev approved these changes

2024-07-30 05:01 UTC, merged