Specify a single location or a specific region for a custom switch block
verilog-to-routing/vtr-verilog-to-routing pull request #2664
Opened 2024-07-25 15:17 UTC by saaramahmoudi

This PR generalize the custom switch block description to allow the user to specify a exact (x,y) location for the switch block by setting type="XY_SPECIFIED", the exact syntax is explained below:

- You should set the switch block type to XY_SPECIFIED (upper case), the other options are: EVERYWHERE, CORNER, ..
- Once you set the type to XY_SPECIFIED, you can put an exact location by setting a "x" and "y" attribute, for example: x="1" y="2"
- If you want to specify a complete row, you can set "x" to -1, for example: x="-1" y="2"
- if you want to specify a complete column, you can set "y" to -1, for example: x="2" y="-1"
- If you want to specify a part of grid, you can specify a region using regular expression documented here: https://mithro-vtr.readthedocs.io/en/latest/arch/reference.html#tag-%3Cregiontype= (please search for word "region" in layout documentation)

#### How Has This Been Tested?
The x and y attribute is tested by @petergrossmann21, and the region description is tested by myself.  

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [ ] All new and existing tests passed

I will add a new test and update documentation later today, but I have created the PR to start the review process.

2024-07-25 15:20 UTC, vaughnbetz commented
Thanks @saaramahmoudi . I'll review shortly. Can you also please update the documentation and add it to this PR?

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +                if (sb_not_here(grid, x_coord, y_coord, sb.location, sb.x, sb.y, sb.reg_x, sb.reg_y)) {
The number of arguments can be reduce by passing sb by reference

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +
can you please change the for loop that iterates over switchblocks to a range-based for loop that iterate over elements by reference?

Github doesn't allow me to add the comment there (line 323)

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +static bool sb_not_here(const DeviceGrid& grid, int x, int y, e_sb_location location, int sb_x, int sb_y, const e_sb_loc_spec& sb_reg_x, const e_sb_loc_spec& sb_reg_y);
replace newly added args with a const t_switchblock_inf& arg

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +static bool match_sb_xy(const DeviceGrid& grid, int x, int y, int sb_x, int sb_y, const e_sb_loc_spec& sb_reg_x, const e_sb_loc_spec& sb_reg_y);
replace newly added args with a const t_switchblock_inf& arg

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +            if(match_sb_xy(grid, x, y, sb_x, sb_y, sb_reg_x, sb_reg_y)){
add space between if and (
between ) and {

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +
remove this empty line to be consistent with the rest of cases

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +    if(sb_x != -1 || sb_y != -1){
add spaces to all if statements in this function

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +        //calculate the appropiate region based on the repeatx/repeaty and current location.
appropiate --> appropriate

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +        y_reg_step = (y_reg_step < 0) ? 0 : y_reg_step;
use std::max(0, value)

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +    if(sb_x != -1 || sb_y != -1){
Can't the outer if statement be removed?

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +    //or the exact y location (will apply it to all rows)
When we know the exact x location while y is not specified, doesn't this mean that we know the column and apply it all the rows?

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +        //    calculated region is valid.
a few typos
is is --> do
necessary --> necessarily
crossponds -- > correspond
is valid --> are valid

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +            if((y + reg_startx) % sb_reg_x.incr == 0){
shouldn't this be x + reg_startx?

2024-07-27 23:40 UTC, soheilshahrouz commented on vpr/src/route/build_switchblocks.cpp
> +        if (x >= reg_startx && x <= reg_endx){ //should fall into the region
these nested if statements are a little hard to read
I think the whole check can be implemented in a single if statement

2024-07-27 23:40 UTC, soheilshahrouz commented on libs/libarchfpga/src/read_xml_arch_file.cpp
> +                sb.reg_x.start = startx_attr.empty() ? 0 : p.parse_formula(startx_attr.value(), vars);
Other functions in this file do not seem to parse formulas when reading the architecture file. Instead they store formulas in std:string member variables and parse them later.

2024-07-28 01:18 UTC, petergrossmann21 requested changes
@saaramahmoudi Can you include the tests that verify this feature in the PR?

2024-08-09 02:35 UTC, vaughnbetz requested changes
Some comments to address (mine partially overlap Soheil's).
Also, it would be good to make the documentation update now, as part of this PR as well. That also might help clarify the precise meaning of repeat and increment (as would comments on the structure data members storing the sb_loc information).

2024-08-09 02:35 UTC, vaughnbetz commented on vpr/src/route/build_switchblocks.cpp
> +        int x_reg_step = (sb_reg_x.repeat != 0) ? (x - sb_reg_x.start) / sb_reg_x.repeat : sb_reg_x.start;
I'm not following the logic very clearly here. Clearly defining what .repeat and .start mean in the structure definition would help, as would a bit more of an overview of the logic here.

2024-08-09 02:35 UTC, vaughnbetz commented on vpr/src/route/build_switchblocks.cpp
> +            if((y + reg_startx) % sb_reg_x.incr == 0){
Agreed.

2024-09-19 17:50 UTC, petergrossmann21 commented
@saaramahmoudi I don't see any new files related to testing; is there something that still needs to be added?

2024-09-19 18:14 UTC, saaramahmoudi commented
@petergrossmann21 @vaughnbetz I am so sorry, but I have been busy doing a different task at work. I am trying my best to land this PR as soon as possible. It might take two-three weeks.

2024-10-04 14:55 UTC, vaughnbetz commented
@saaramahmoudi : I think this is ready to merge, but I just merged a libcatch2 update that caused a conflict (sorry!).  If you fix that conflict I think this is good to go.

2024-10-06 22:48 UTC, saaramahmoudi commented
@vaughnbetz 
Here is the link to Titan_quick_qor benchmarks: [Titan](https://docs.google.com/spreadsheets/d/10fMlD4YQVFGoVXUgq9RRG808WQGaqn5v34SFwhJWges/edit?usp=sharing)

2024-10-07 02:34 UTC, vaughnbetz commented
QoR looks good, thanks.

2024-10-07 15:52 UTC, saaramahmoudi commented
@vaughnbetz This branch is also ready to merge

2024-10-08 00:44 UTC, merged

2024-10-08 00:44 UTC, vaughnbetz commented
Thanks @saaramahmoudi !