[AP] Added Partial Placement Object
verilog-to-routing/vtr-verilog-to-routing pull request #2742
Opened 2024-09-23 22:20 UTC by AlexandreSinger

Added the partial placement object. This object is used during the Analytical Placement flow to store the positions of the APBlocks. This placement is not gaurenteed to be legal; however, it does gaurentee that the blocks are placed on the device and the fixed blocks are placed in valid locations.

2024-09-26 15:05 UTC, vaughnbetz requested changes
Looks good; a few suggested changes.

2024-09-26 15:17 UTC, AlexandreSinger commented on vpr/src/analytical_place/partial_placement.h
> +    /// @brief The x locations of all the APBlocks
That is all correct. I have updated the comment in the class (I felt that was a good place to put it).

2024-09-26 15:17 UTC, AlexandreSinger commented on vpr/src/analytical_place/partial_placement.h
> +            : block_x_locs(netlist.blocks().size(), -1.f),
Ah! That is a very good catch! These were originally floats, but you are right about doubles being better for Eigen.

2024-09-26 15:19 UTC, AlexandreSinger commented on vpr/src/analytical_place/partial_placement.h
> +                block_sub_tiles[blk_id] = loc.sub_tile;
That is correct; however, I wanted to design the Partial Placement object to be ignorant to the choices of the flow. It does not care that on the outside people may or may not allow x to be constrained by not y, it should work regardless! There is an assert in the APNetlist now (from another PR) which will cover this case though.

2024-09-26 15:21 UTC, vaughnbetz commented on vpr/src/analytical_place/partial_placement.h
> +                block_sub_tiles[blk_id] = loc.sub_tile;
OK, sounds good.

2024-09-27 03:49 UTC, vaughnbetz approved these changes
Looks good, thanks.

2024-09-27 03:49 UTC, merged